// <auto-generated />
using System;
using APIFinal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIFinal.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250515110904_add-itemdesc")]
    partial class additemdesc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIFinal.Models.ArchivedTransactions", b =>
                {
                    b.Property<int>("archiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("archiveID"));

                    b.Property<string>("Clasification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Copies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCond")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurQTY")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<string>("archiveDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("archiveID");

                    b.ToTable("ArchievedTransactions");
                });

            modelBuilder.Entity("APIFinal.Models.Custodian", b =>
                {
                    b.Property<string>("CSTCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CSTName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DPRName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CSTCode");

                    b.ToTable("Custodians");
                });

            modelBuilder.Entity("APIFinal.Models.ICS", b =>
                {
                    b.Property<int>("ICSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ICSID"));

                    b.Property<string>("CSTCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundCluster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICSName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ICSPrice")
                        .HasColumnType("float");

                    b.Property<DateOnly>("ICSSDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IcsDateReceived")
                        .HasColumnType("date");

                    b.Property<int>("ItemCode")
                        .HasColumnType("int");

                    b.Property<int>("Life")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("ICSID");

                    b.ToTable("ICS");
                });

            modelBuilder.Entity("APIFinal.Models.ItemDisposal", b =>
                {
                    b.Property<string>("NonServCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("disposalDate")
                        .HasColumnType("date");

                    b.Property<string>("disposalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NonServCode");

                    b.ToTable("ItemDisposal");
                });

            modelBuilder.Entity("APIFinal.Models.Items", b =>
                {
                    b.Property<int>("ItemCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemCode"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LifeTime")
                        .HasColumnType("int");

                    b.Property<bool>("NonServ")
                        .HasColumnType("bit");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("Servicable")
                        .HasColumnType("bit");

                    b.Property<int>("isnotonBorrow")
                        .HasColumnType("int");

                    b.Property<int>("isonBorrow")
                        .HasColumnType("int");

                    b.HasKey("ItemCode");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("APIFinal.Models.PAR", b =>
                {
                    b.Property<string>("ParID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DprHeadName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundCls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemCode")
                        .HasColumnType("int");

                    b.Property<string>("ItemDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParQty")
                        .HasColumnType("int");

                    b.Property<string>("SourceCopies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("refNo")
                        .HasColumnType("int");

                    b.Property<float>("value")
                        .HasColumnType("real");

                    b.HasKey("ParID");

                    b.ToTable("PAR");
                });

            modelBuilder.Entity("APIFinal.Models.Transfer", b =>
                {
                    b.Property<int>("PtrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PtrId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CstCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("approvedByDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apprvdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateAcquired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("dateTransferred")
                        .HasColumnType("date");

                    b.Property<string>("designationOf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("designationReceived")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("designationRelease")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("from")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fundccl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receivedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receivedByDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("releaseBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("releaseByDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rvName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PtrId");

                    b.ToTable("Transfer");
                });
#pragma warning restore 612, 618
        }
    }
}
