// <auto-generated />
using System;
using APIFinal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIFinal.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIFinal.Models.ArchivedTransactions", b =>
                {
                    b.Property<int>("archiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("archiveID"));

                    b.Property<string>("DprName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCond")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurQTY")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<DateOnly>("archiveDate")
                        .HasColumnType("date");

                    b.HasKey("archiveID");

                    b.ToTable("ArchievedTransactions");
                });

            modelBuilder.Entity("APIFinal.Models.Custodian", b =>
                {
                    b.Property<string>("CSTCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CSTName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DPRName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CSTCode");

                    b.ToTable("Custodians");
                });

            modelBuilder.Entity("APIFinal.Models.ICS", b =>
                {
                    b.Property<int>("ICSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ICSID"));

                    b.Property<string>("CSTCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICSName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ICSPrice")
                        .HasColumnType("float");

                    b.Property<DateOnly>("IcsDate")
                        .HasColumnType("date");

                    b.Property<int>("ItemCode")
                        .HasColumnType("int");

                    b.Property<int>("Life")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("ICSID");

                    b.ToTable("ICS");
                });

            modelBuilder.Entity("APIFinal.Models.ItemDisposal", b =>
                {
                    b.Property<string>("NonServCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("disposalDate")
                        .HasColumnType("date");

                    b.Property<string>("disposalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NonServCode");

                    b.ToTable("ItemDisposal");
                });

            modelBuilder.Entity("APIFinal.Models.Items", b =>
                {
                    b.Property<int>("ItemCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemCode"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NonServ")
                        .HasColumnType("bit");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("Servicable")
                        .HasColumnType("bit");

                    b.Property<int>("isnotonBorrow")
                        .HasColumnType("int");

                    b.Property<int>("isonBorrow")
                        .HasColumnType("int");

                    b.HasKey("ItemCode");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("APIFinal.Models.PAR", b =>
                {
                    b.Property<string>("ParID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DprName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemCode")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParQty")
                        .HasColumnType("int");

                    b.Property<int>("refNo")
                        .HasColumnType("int");

                    b.HasKey("ParID");

                    b.ToTable("PAR");
                });

            modelBuilder.Entity("APIFinal.Models.Transfer", b =>
                {
                    b.Property<int>("PtrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PtrId"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CstCode")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("dateTransferred")
                        .HasColumnType("date");

                    b.Property<string>("receiveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PtrId");

                    b.ToTable("Transfer");
                });
#pragma warning restore 612, 618
        }
    }
}
